config/routes.rb
Rails.application.routes.draw do
  root "tracks#index"

  resources :tracks, only: %i[index show update] do
    resources :track_tags, only: %i[index create destroy]
  end

  resources :session, only: %i[new create destroy]
  resources :spotify_playlists, only: %i[new create]

  # admin
  resources :lidarr_instances
  resources :tags
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/lidarr_instance.rb
require "#{Rails.root}/lib/lidarr"
class LidarrInstance < ApplicationRecord
  before_validation :set_defaults, on: :create

  validates :name, presence: true
  validates :host, presence: true
  validates :api_key, presence: true
  validates :root_folder_path, presence: true
  validates :metadata_profile_id, presence: true
  validates :quality_profile_id, presence: true

  def set_defaults
    root_folder = client.root_folders.first
    raise "No root folder found" unless root_folder

    self.root_folder_path = root_folder.path
    self.metadata_profile_id = root_folder.default_metadata_profile_id
    self.quality_profile_id = root_folder.default_quality_profile_id
  end

  def client
    @client ||= Lidarr::Client.new(host, api_key)
  end
end

app/controllers/lidarr_instances_controller.rb
class LidarrInstancesController < ApplicationController
  before_action :set_lidarr_instance, only: %i[ show edit update destroy ]
  authenticate_roles :admin

  # GET /lidarr_instances or /lidarr_instances.json
  def index
    @lidarr_instances = LidarrInstance.all
  end

  # GET /lidarr_instances/1 or /lidarr_instances/1.json
  def show
  end

  # GET /lidarr_instances/new
  def new
    @lidarr_instance = LidarrInstance.new
  end

  # GET /lidarr_instances/1/edit
  def edit
  end

  # POST /lidarr_instances or /lidarr_instances.json
  def create
    @lidarr_instance = LidarrInstance.new(lidarr_instance_params)

    respond_to do |format|
      if @lidarr_instance.save
        format.html { redirect_to @lidarr_instance, notice: "Lidarr instance was successfully created." }
        format.json { render :show, status: :created, location: @lidarr_instance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lidarr_instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lidarr_instances/1 or /lidarr_instances/1.json
  def update
    respond_to do |format|
      if @lidarr_instance.update(lidarr_instance_params)
        format.html { redirect_to @lidarr_instance, notice: "Lidarr instance was successfully updated." }
        format.json { render :show, status: :ok, location: @lidarr_instance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lidarr_instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lidarr_instances/1 or /lidarr_instances/1.json
  def destroy
    @lidarr_instance.destroy!

    respond_to do |format|
      format.html { redirect_to lidarr_instances_path, status: :see_other, notice: "Lidarr instance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lidarr_instance
      @lidarr_instance = LidarrInstance.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def lidarr_instance_params
      params.expect(lidarr_instance: [ :host, :name, :api_key, :quality_profile_id, :metadata_profile_id, :root_folder_path, :tags ])
    end
end

app/helpers/lidarr_instances_helper.rb
module LidarrInstancesHelper
end

app/views/lidarr_instances/_form.html.erb
<%= form_with(model: lidarr_instance, class: "contents") do |form| %>
  <% if lidarr_instance.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(lidarr_instance.errors.count, "error") %> prohibited this lidarr_instance from being saved:</h2>

      <ul class="list-disc ml-6">
        <% lidarr_instance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :host %>
    <%= form.text_field :host, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": lidarr_instance.errors[:host].none?, "border-red-400 focus:outline-red-600": lidarr_instance.errors[:host].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": lidarr_instance.errors[:name].none?, "border-red-400 focus:outline-red-600": lidarr_instance.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :api_key %>
    <%= form.text_field :api_key, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": lidarr_instance.errors[:api_key].none?, "border-red-400 focus:outline-red-600": lidarr_instance.errors[:api_key].any?}] %>
  </div>

  <% unless lidarr_instance.new_record? %>
    <div class="my-5">
      <%= form.label :quality_profile_id %>
      <%= form.number_field :quality_profile_id, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": lidarr_instance.errors[:quality_profile_id].none?, "border-red-400 focus:outline-red-600": lidarr_instance.errors[:quality_profile_id].any?}] %>
    </div>

    <div class="my-5">
      <%= form.label :metadata_profile_id %>
      <%= form.number_field :metadata_profile_id, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": lidarr_instance.errors[:metadata_profile_id].none?, "border-red-400 focus:outline-red-600": lidarr_instance.errors[:metadata_profile_id].any?}] %>
    </div>

    <div class="my-5">
      <%= form.label :root_folder_path %>
      <%= form.text_field :root_folder_path, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": lidarr_instance.errors[:root_folder_path].none?, "border-red-400 focus:outline-red-600": lidarr_instance.errors[:root_folder_path].any?}] %>
    </div>

    <div class="my-5">
      <%= form.label :tags %>
      <%= form.text_field :tags, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": lidarr_instance.errors[:tags].none?, "border-red-400 focus:outline-red-600": lidarr_instance.errors[:tags].any?}] %>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/lidarr_instances/_lidarr_instance.html.erb
<div id="<%= dom_id lidarr_instance %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Host:</strong>
    <%= lidarr_instance.host %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= lidarr_instance.name %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Api key:</strong>
    <%= lidarr_instance.api_key %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Quality profile:</strong>
    <%= lidarr_instance.quality_profile_id %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Metadata profile:</strong>
    <%= lidarr_instance.metadata_profile_id %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Root folder path:</strong>
    <%= lidarr_instance.root_folder_path %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Tags:</strong>
    <%= lidarr_instance.tags %>
  </p>
</div>

app/views/lidarr_instances/edit.html.erb
<% content_for :title, "Editing lidarr instance" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing lidarr instance</h1>

  <%= render "form", lidarr_instance: @lidarr_instance %>

  <%= link_to "Show this lidarr instance", @lidarr_instance, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to lidarr instances", lidarr_instances_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/lidarr_instances/index.html.erb
<% content_for :title, "Lidarr instances" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Lidarr instances</h1>
    <%= link_to "New lidarr instance", new_lidarr_instance_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="lidarr_instances" class="min-w-full">
    <% if @lidarr_instances.any? %>
      <% @lidarr_instances.each do |lidarr_instance| %>
        <%= render lidarr_instance %>
        <p>
          <%= link_to "Show this lidarr instance", lidarr_instance, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
        </p>
      <% end %>
    <% else %>
      <p class="text-center my-10">No lidarr instances found.</p>
    <% end %>
  </div>
</div>

app/views/lidarr_instances/new.html.erb
<% content_for :title, "New lidarr instance" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New lidarr instance</h1>

  <%= render "form", lidarr_instance: @lidarr_instance %>

  <%= link_to "Back to lidarr instances", lidarr_instances_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/lidarr_instances/show.html.erb
<% content_for :title, "Showing lidarr instance" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing lidarr instance</h1>

  <%= render @lidarr_instance %>

  <%= link_to "Edit this lidarr instance", edit_lidarr_instance_path(@lidarr_instance), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to lidarr instances", lidarr_instances_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this lidarr instance", @lidarr_instance, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>
</div>