config/routes.rb
Rails.application.routes.draw do
  root "tracks#index"

  resources :tracks, only: %i[index show update] do
    resources :track_tags, only: %i[index create destroy]
  end

  resources :session, only: %i[new create destroy]
  resources :spotify_playlists, only: %i[new create]

  # admin
  resources :lidarr_instances
  resources :tags
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/spotify_playlist.rb
class SpotifyPlaylist < ApplicationRecord
  after_create :download_playlist

  SPOTIFY_API_URL = "https://api.spotify.com/v1"
  CLIENT_ID = ENV["SPOTIFY_CLIENT_ID"]
  CLIENT_SECRET = ENV["SPOTIFY_CLIENT_SECRET"]

  def playlist_id
    @playlist_id ||= URI.parse(url).path.split("/").last
  end

  def download_playlist
    response = spotify_client.get("playlists/#{playlist_id}?market=US")
    playlist = JSON.parse(response.body)
    playlist["tracks"]["items"].each do |item|
      track = item["track"]

      artist = Artist.find_or_create_by(spotify_id: track["artists"].first["id"]).tap do |artist|
        artist.update(name: track["artists"].first["name"])
      end

      album = Album.find_or_create_by(spotify_id: track["album"]["id"]).tap do |album|
        album.update(name: track["album"]["name"], artist: artist)
      end

      Track.find_or_create_by(spotify_id: track["id"]).update(name: track["name"], album: album)
    end
  end

  def spotify_client
    @spotify_client || Faraday.new(SPOTIFY_API_URL) do |conn|
      conn.headers["Authorization"] = "Bearer #{access_token}"
      conn.headers["Accept"] = "application/json"
      conn.headers["Content-Type"] = "application/json"
    end
  end

  def access_token
    resp = Faraday.new("https://accounts.spotify.com/api/token") do |conn|
      conn.params["client_id"] = CLIENT_ID
      conn.params["client_secret"] = CLIENT_SECRET
      conn.params["grant_type"] = "client_credentials"
    end.post
    JSON.parse(resp.body)["access_token"]
  end
end

app/controllers/spotify_playlists_controller.rb
class SpotifyPlaylistsController < ApplicationController
  before_action :set_spotify_playlist, only: %i[ show edit update destroy ]

  # GET /spotify_playlists or /spotify_playlists.json
  def index
    @spotify_playlists = SpotifyPlaylist.all
  end

  # GET /spotify_playlists/1 or /spotify_playlists/1.json
  def show
  end

  # GET /spotify_playlists/new
  def new
    @spotify_playlist = SpotifyPlaylist.new
  end

  # GET /spotify_playlists/1/edit
  def edit
  end

  # POST /spotify_playlists or /spotify_playlists.json
  def create
    @spotify_playlist = SpotifyPlaylist.new(spotify_playlist_params)

    respond_to do |format|
      if @spotify_playlist.save
        format.html { redirect_to tracks_path, notice: "Spotify playlist was successfully created." }
        format.json { render :show, status: :created, location: @spotify_playlist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @spotify_playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spotify_playlists/1 or /spotify_playlists/1.json
  def update
    respond_to do |format|
      if @spotify_playlist.update(spotify_playlist_params)
        format.html { redirect_to @spotify_playlist, notice: "Spotify playlist was successfully updated." }
        format.json { render :show, status: :ok, location: @spotify_playlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spotify_playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spotify_playlists/1 or /spotify_playlists/1.json
  def destroy
    @spotify_playlist.destroy!

    respond_to do |format|
      format.html { redirect_to spotify_playlists_path, status: :see_other, notice: "Spotify playlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spotify_playlist
      @spotify_playlist = SpotifyPlaylist.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def spotify_playlist_params
      params.expect(spotify_playlist: [ :url ])
    end
end

app/helpers/spotify_playlists_helper.rb
module SpotifyPlaylistsHelper
end

app/views/spotify_playlists/_form.html.erb
<%= form_with(model: spotify_playlist, class: "contents") do |form| %>
  <% if spotify_playlist.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(spotify_playlist.errors.count, "error") %> prohibited this spotify_playlist from being saved:</h2>

      <ul class="list-disc ml-6">
        <% spotify_playlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :url, 'URL' %>
    <%= form.text_field :url, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": spotify_playlist.errors[:url].none?, "border-red-400 focus:outline-red-600": spotify_playlist.errors[:url].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/spotify_playlists/_spotify_playlist.html.erb
<div id="<%= dom_id spotify_playlist %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Url:</strong>
    <%= spotify_playlist.url %>
  </p>
</div>

app/views/spotify_playlists/edit.html.erb
<% content_for :title, "Editing spotify playlist" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing spotify playlist</h1>

  <%= render "form", spotify_playlist: @spotify_playlist %>

  <%= link_to "Show this spotify playlist", @spotify_playlist, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to spotify playlists", spotify_playlists_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/spotify_playlists/index.html.erb
<% content_for :title, "Spotify playlists" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Spotify playlists</h1>
    <%= link_to "New spotify playlist", new_spotify_playlist_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="spotify_playlists" class="min-w-full">
    <% if @spotify_playlists.any? %>
      <% @spotify_playlists.each do |spotify_playlist| %>
        <%= render spotify_playlist %>
        <p>
          <%= link_to "Show this spotify playlist", spotify_playlist, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
        </p>
      <% end %>
    <% else %>
      <p class="text-center my-10">No spotify playlists found.</p>
    <% end %>
  </div>
</div>

app/views/spotify_playlists/new.html.erb
<% content_for :title, "New spotify playlist" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New spotify playlist</h1>

  <%= render "form", spotify_playlist: @spotify_playlist %>
</div>

app/views/spotify_playlists/show.html.erb
<% content_for :title, "Showing spotify playlist" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing spotify playlist</h1>

  <%= render @spotify_playlist %>

  <%= link_to "Edit this spotify playlist", edit_spotify_playlist_path(@spotify_playlist), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to spotify playlists", spotify_playlists_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this spotify playlist", @spotify_playlist, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>
</div>