config/routes.rb
Rails.application.routes.draw do
  root "tracks#index"

  resources :tracks, only: %i[index show update] do
    resources :track_tags, only: %i[index create destroy]
  end

  resources :session, only: %i[new create destroy]
  resources :spotify_playlists, only: %i[new create]

  # admin
  resources :lidarr_instances
  resources :tags
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/track_tag.rb
class TrackTag < ApplicationRecord
  belongs_to :track
  belongs_to :tag
end

app/controllers/track_tags_controller.rb
class TrackTagsController < ApplicationController
  before_action :set_track
  before_action :set_track_tag, only: %i[ destroy ]

  # GET /track_tags or /track_tags.json
  def index
    @set_track_tags = @track.track_tags
    @unset_track_tags = Tag.all - @track.tags
  end

  def create
    @track_tag = TrackTag.new(track_tag_params)

    if @track_tag.save
      redirect_to track_track_tags_path, notice: "Track tag was successfully created."
    else
      redirect_to track_track_tags_path, notice: "Track tag was not created."
    end
  end

  def destroy
    @track_tag.destroy!

    redirect_to track_track_tags_path, status: :see_other, notice: "Track tag was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_track_tag
    @track_tag = @track.track_tags.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def track_tag_params
    params.expect(track_tag: [ :track_id, :tag_id ])
  end

  def set_track
    @track = Track.find(params[:track_id])
  end
end

app/helpers/track_tags_helper.rb
module TrackTagsHelper
end

app/views/track_tags/_form.html.erb
<%= form_with(model: track_tag, class: "contents") do |form| %>
  <% if track_tag.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(track_tag.errors.count, "error") %> prohibited this track_tag from being saved:</h2>

      <ul class="list-disc ml-6">
        <% track_tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :track_id %>
    <%= form.text_field :track_id, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": track_tag.errors[:track_id].none?, "border-red-400 focus:outline-red-600": track_tag.errors[:track_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :tag_id %>
    <%= form.text_field :tag_id, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": track_tag.errors[:tag_id].none?, "border-red-400 focus:outline-red-600": track_tag.errors[:tag_id].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/track_tags/_track_tag.html.erb
<div id="<%= dom_id track_tag %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Track:</strong>
    <%= track_tag.track_id %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Tag:</strong>
    <%= track_tag.tag_id %>
  </p>
</div>

app/views/track_tags/edit.html.erb
<% content_for :title, "Editing track tag" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing track tag</h1>

  <%= render "form", track_tag: @track_tag %>

  <%= link_to "Show this track tag", @track_tag, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to track tags", track_tags_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/track_tags/index.html.erb
<% content_for :title, "Track tags" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Track tags</h1>
  </div>

  <div id="track_tags" class="min-w-full">
    <h3 class="font-bold text-lg mt-4">Set tags</h3>
    <% @set_track_tags.each do |tag| %>
      <%= button_to tag.tag.name, track_track_tag_path(id: tag.id), method: :delete, class: "btn pill btn-#{ tag.tag.color }" %>
    <% end %>
    <div class="mt-4"></div>
    <h3 class="font-bold text-lg mt-4">Available tags</h3>
    <% @unset_track_tags.each do |tag| %>
      <%= button_to tag.name, track_track_tags_path(track_tag: { track_id: @track, tag_id: tag }), method: :post, class: "py-2 px-4 shadow-md no-underline rounded-full bg-#{ tag.color } text-white font-sans font-semibold text-sm border-#{ tag.color } btn-primary hover:text-white hover:bg-#{ tag.color }-light focus:outline-none active:shadow-none mr-2" %>
    <% end %>
  </div>
</div>

app/views/track_tags/new.html.erb
<% content_for :title, "New track tag" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New track tag</h1>

  <%= render "form", track_tag: @track_tag %>

  <%= link_to "Back to track tags", track_tags_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/track_tags/show.html.erb
<% content_for :title, "Showing track tag" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing track tag</h1>

  <%= render @track_tag %>

  <%= link_to "Edit this track tag", edit_track_tag_path(@track_tag), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to track tags", track_tags_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this track tag", @track_tag, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>
</div>